"""Example tests for the Test Harness."""

from translator_testing_model.datamodel.pydanticmodel import TestSuite

example_test_cases = TestSuite.parse_obj(
    {
        "id": "TestSuite_1",
        "name": None,
        "description": None,
        "tags": [],
        "test_metadata": {
            "id": "1",
            "name": None,
            "description": None,
            "tags": [],
            "test_source": "SMURF",
            "test_reference": None,
            "test_objective": "AcceptanceTest",
            "test_annotations": [],
        },
        "test_cases": {
            "TestCase_1": {
                "id": "TestCase_1",
                "name": "what treats MONDO:0010794",
                "description": "Valproic_Acid_treats_NARP_Syndrome; Barbiturates_treats_NARP_Syndrome",
                "tags": [],
                "test_env": "ci",
                "query_type": None,
                "test_assets": [
                    {
                        "id": "Asset_3",
                        "name": "Valproic_Acid_treats_NARP_Syndrome",
                        "description": "Valproic_Acid_treats_NARP_Syndrome",
                        "tags": [],
                        "input_id": "MONDO:0010794",
                        "input_name": "NARP Syndrome",
                        "input_category": "biolink:Disease",
                        "predicate_id": "biolink:treats",
                        "predicate_name": "treats",
                        "output_id": "DRUGBANK:DB00313",
                        "output_name": "Valproic Acid",
                        "output_category": None,
                        "association": None,
                        "qualifiers": [],
                        "expected_output": "NeverShow",
                        "test_issue": None,
                        "semantic_severity": None,
                        "in_v1": None,
                        "well_known": False,
                        "test_reference": None,
                        "test_runner_settings": ["inferred"],
                        "test_metadata": {
                            "id": "1",
                            "name": None,
                            "description": None,
                            "tags": [],
                            "test_source": "SMURF",
                            "test_reference": "https://github.com/NCATSTranslator/Feedback/issues/147",
                            "test_objective": "AcceptanceTest",
                            "test_annotations": [],
                        },
                    },
                    {
                        "id": "Asset_4",
                        "name": "Barbiturates_treats_NARP_Syndrome",
                        "description": "Barbiturates_treats_NARP_Syndrome",
                        "tags": [],
                        "input_id": "MONDO:0010794",
                        "input_name": "NARP Syndrome",
                        "input_category": "biolink:Disease",
                        "predicate_id": "biolink:treats",
                        "predicate_name": "treats",
                        "output_id": "MESH:D001463",
                        "output_name": "Barbiturates",
                        "output_category": None,
                        "association": None,
                        "qualifiers": [],
                        "expected_output": "NeverShow",
                        "test_issue": None,
                        "semantic_severity": None,
                        "in_v1": None,
                        "well_known": False,
                        "test_reference": None,
                        "test_runner_settings": ["inferred"],
                        "test_metadata": {
                            "id": "1",
                            "name": None,
                            "description": None,
                            "tags": [],
                            "test_source": "SMURF",
                            "test_reference": "https://github.com/NCATSTranslator/Feedback/issues/147",
                            "test_objective": "AcceptanceTest",
                            "test_annotations": [],
                        },
                    },
                ],
                "preconditions": [],
                "trapi_template": None,
                "components": ["ars"],
                "test_case_objective": "AcceptanceTest",
                "test_case_source": None,
                "test_case_predicate_name": "treats",
                "test_case_predicate_id": "biolink:treats",
                "test_case_input_id": "MONDO:0010794",
                "test_runner_settings": ["inferred"],
            },
            "TestCase_2": {
                "id": "TestCase_2",
                "name": "imatinib to asthma",
                "description": "imatinib to asthma",
                "tags": [],
                "test_runner_settings": ["pathfinder"],
                "query_type": None,
                "test_assets": [
                    {
                        "id": "PTFQ_1",
                        "name": "Imatinib to Asthma",
                        "description": "Imatinib to Asthma",
                        "tags": [],
                        "test_runner_settings": ["pathfinder"],
                        "source_input_id": "CHEBI:31690",
                        "source_input_name": "Imatinib",
                        "source_input_category": "biolink:Drug",
                        "target_input_id": "MONDO:0004979",
                        "target_input_name": "Asthma",
                        "target_input_category": "biolink:Disease",
                        "predicate_id": "biolink:related_to",
                        "predicate_name": "related to",
                        "minimum_required_path_nodes": 2,
                        "path_nodes": [
                            {"ids": ["NCBIGene:3815"], "name": "KIT"},
                            {
                                "ids": ["CHEBI:18295", "PR:000049994"],
                                "name": "Histamine",
                            },
                            {"ids": ["NCBIGene:4254"], "name": "SCF-1"},
                            {"ids": ["CL:0000097"], "name": "Mast Cell"},
                        ],
                        "association": None,
                        "qualifiers": None,
                        "expected_output": "TopAnswer",
                        "test_issue": None,
                        "semantic_severity": None,
                        "in_v1": None,
                        "well_known": False,
                        "test_reference": None,
                        "test_metadata": {
                            "id": "1",
                            "name": None,
                            "description": None,
                            "tags": [],
                            "test_runner_settings": [],
                            "test_source": "SMURF",
                            "test_reference": None,
                            "test_objective": "AcceptanceTest",
                            "test_annotations": [],
                        },
                    }
                ],
                "preconditions": [],
                "trapi_template": None,
                "test_case_objective": "AcceptanceTest",
                "test_case_source": None,
                "components": ["ars"],
                "test_env": "ci",
            },
        },
    }
).test_cases
